# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QDPCqsMkcsv2mDVTeCADgg-TR3Ucoe95
"""

import pandas as pd

diabetes=pd.read_csv('https://github.com/YBIFoundation/Dataset/raw/main/Diabetes.csv')
diabetes

diabetes.columns

y=diabetes['diabetes']
x=diabetes[['pregnancies', 'glucose', 'diastolic', 'triceps', 'insulin', 'bmi','dpf', 'age', 'diabetes']]

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.7,random_state=1584)

from sklearn.linear_model import LogisticRegression
model=LogisticRegression(max_iter=600)

model.fit(x_train,y_train)

y_pred=model.predict(x_test)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

